name: Auto Deploy Firebase Functions
on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        run: npm install
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v13.25.0
        with:
          args: deploy --only functions:generateProductImage,functions:autoGenerateImage
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
